const arrayTreeFilter = <T>(
  data: T[],
  filterFn: (item: T, level: number) => boolean,
  options?: {
    childrenKeyName?: string
  },
) => {
  options = options || {}
  options.childrenKeyName = options.childrenKeyName || 'children'
  let children = data || []
  const result: T[] = []
  let level = 0
  do {
    const foundItem: T = children.filter(function (item) {
      return filterFn(item, level)
    })[0]
    if (!foundItem) {
      break
    }
    result.push(foundItem)
    children = (foundItem as any)[options.childrenKeyName] || []
    level += 1
  } while (children.length > 0)
  return result
}

/**
 * 树形过滤
 * @author waldon
 * @date 2022-12-08
 * @link https://stackblitz.com/edit/js-emywe9?file=index.js
 */
function filter(array: any[], text: string) {
  const getNodes = (pre: any[], cur: any) => {
    if (cur.name.includes(text)) {
      pre.push(cur)
      return pre
    }
    if (Array.isArray(cur.children)) {
      const children = cur.children.reduce(getNodes, [])
      if (children.length) {
        pre.push({ ...cur, children })
      }
    }
    return pre
  }
  return array.reduce(getNodes, [])
}

const tree = [
  {
    id: 55,
    pid: 0,
    menu_type: 2,
    name: '主页',
    icon: 'HomeOutlined',
    sort: 2,
    is_hide: 1,
    route_path: '/home',
    api: '/',
    is_iframe: 0,
    iframe_url: '',
    createdat: '2022-07-20 16:34:14',
    updatedat: '2022-08-23 15:00:03',
    role_ids: null,
    parent_ids: [0, 55],
    admin: 'duanya',
    component: 'home/index',
    target: '',
    redirect: '',
    key: 55,
    children: [],
  },
  {
    id: 1,
    pid: 0,
    menu_type: 1,
    name: '系统',
    icon: 'GlobalOutlined',
    sort: 1,
    is_hide: 1,
    route_path: '/system',
    api: '/',
    is_iframe: 0,
    iframe_url: '',
    createdat: '2022-07-04 18:28:10',
    updatedat: '2022-08-23 14:37:36',
    role_ids: [16, 14, 13],
    parent_ids: [0, 1],
    admin: '',
    component: 'RouteView',
    target: '',
    redirect: '/system/menu/menu-list',
    key: 1,
    children: [
      {
        id: 4,
        pid: 1,
        menu_type: 2,
        name: '菜单管理',
        icon: 'CalendarOutlined',
        sort: 10,
        is_hide: 1,
        route_path: '/system/menu/menu-list',
        api: '/api/v1/system/menu/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-04 18:29:53',
        updatedat: '2022-08-24 14:21:59',
        role_ids: [13],
        parent_ids: [0, 1, 4],
        admin: '',
        component: 'system/menu/menu-list',
        target: '',
        redirect: '/system/menu/menu-list',
        key: 4,
        children: [
          {
            id: 35,
            pid: 4,
            menu_type: 3,
            name: '新增菜单',
            icon: 'TableOutlined',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/add',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-13 09:57:50',
            updatedat: '2022-11-11 14:47:25',
            role_ids: [14, 15, 13],
            parent_ids: [0, 1, 4, 35],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 35,
            children: [],
          },
          {
            id: 57,
            pid: 4,
            menu_type: 3,
            name: '查询全部菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/all',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:26:02',
            updatedat: '2022-07-21 18:26:02',
            role_ids: [14, 13],
            parent_ids: [0, 1, 4, 57],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 57,
            children: [],
          },
          {
            id: 58,
            pid: 4,
            menu_type: 3,
            name: '删除菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/delete',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:26:37',
            updatedat: '2022-07-21 18:26:37',
            role_ids: [14],
            parent_ids: [0, 1, 4, 58],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 58,
            children: [],
          },
          {
            id: 59,
            pid: 4,
            menu_type: 3,
            name: '获取单个菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:27:17',
            updatedat: '2022-07-21 18:27:17',
            role_ids: [14],
            parent_ids: [0, 1, 4, 59],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 59,
            children: [],
          },
          {
            id: 60,
            pid: 4,
            menu_type: 3,
            name: '左侧菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/route',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:28:03',
            updatedat: '2022-07-21 18:28:03',
            role_ids: [14],
            parent_ids: [0, 1, 4, 60],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 60,
            children: [],
          },
          {
            id: 61,
            pid: 4,
            menu_type: 3,
            name: '编辑菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/menu/update',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:28:34',
            updatedat: '2022-07-21 18:28:34',
            role_ids: [14],
            parent_ids: [0, 1, 4, 61],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 61,
            children: [],
          },
        ],
      },
      {
        id: 7,
        pid: 1,
        menu_type: 2,
        name: '菜单统计看板',
        icon: 'CarryOutOutlined',
        sort: 9,
        is_hide: 1,
        route_path: '/system/statistic',
        api: '/api/v1/system/log/board',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-04 18:31:28',
        updatedat: '2022-08-08 15:08:55',
        role_ids: [14],
        parent_ids: [0, 1, 7],
        admin: '',
        component: 'system/statistic/index',
        target: '',
        redirect: '/system/statistic',
        key: 7,
        children: [],
      },
      {
        id: 8,
        pid: 1,
        menu_type: 2,
        name: '角色管理',
        icon: 'ClusterOutlined',
        sort: 8,
        is_hide: 1,
        route_path: '/system/role/role-list',
        api: '/api/v1/system/role/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-04 18:31:34',
        updatedat: '2022-08-08 15:09:28',
        role_ids: [14],
        parent_ids: [0, 1, 8],
        admin: '',
        component: 'system/role/role-list',
        target: '',
        redirect: '/system/role/role-list',
        key: 8,
        children: [
          {
            id: 62,
            pid: 8,
            menu_type: 3,
            name: '添加角色',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/role/add',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:29:37',
            updatedat: '2022-07-21 18:29:37',
            role_ids: [14],
            parent_ids: [0, 1, 8, 62],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 62,
            children: [],
          },
          {
            id: 63,
            pid: 8,
            menu_type: 3,
            name: '删除角色',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/role/delete',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:30:14',
            updatedat: '2022-07-21 18:30:14',
            role_ids: [14],
            parent_ids: [0, 1, 8, 63],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 63,
            children: [],
          },
          {
            id: 64,
            pid: 8,
            menu_type: 3,
            name: '编辑角色',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/role/edit',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:30:42',
            updatedat: '2022-07-21 18:30:42',
            role_ids: [14],
            parent_ids: [0, 1, 8, 64],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 64,
            children: [],
          },
          {
            id: 65,
            pid: 8,
            menu_type: 3,
            name: '获取单个角色',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/role/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:31:06',
            updatedat: '2022-07-21 18:31:06',
            role_ids: [14],
            parent_ids: [0, 1, 8, 65],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 65,
            children: [],
          },
          {
            id: 66,
            pid: 8,
            menu_type: 3,
            name: '角色下拉列表',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/role/role_data',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:36:34',
            updatedat: '2022-07-21 18:36:34',
            role_ids: [14],
            parent_ids: [0, 1, 8, 66],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 66,
            children: [],
          },
          {
            id: 84,
            pid: 8,
            menu_type: 3,
            name: '游戏列表',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/common/game/list',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:51:20',
            updatedat: '2022-07-21 18:51:20',
            role_ids: [14],
            parent_ids: [0, 1, 8, 84],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 84,
            children: [],
          },
        ],
      },
      {
        id: 6,
        pid: 1,
        menu_type: 2,
        name: '用户管理',
        icon: 'UsergroupAddOutlined',
        sort: 7,
        is_hide: 1,
        route_path: '/system/user',
        api: '/api/v1/system/user/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-04 18:30:27',
        updatedat: '2022-08-08 15:09:37',
        role_ids: [14],
        parent_ids: [0, 1, 6],
        admin: '',
        component: 'system/user/index',
        target: '',
        redirect: '/system/user',
        key: 6,
        children: [
          {
            id: 67,
            pid: 6,
            menu_type: 3,
            name: '编辑用户',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/user/edit',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:38:16',
            updatedat: '2022-07-21 18:38:16',
            role_ids: [14],
            parent_ids: [0, 1, 6, 67],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 67,
            children: [],
          },
          {
            id: 68,
            pid: 6,
            menu_type: 3,
            name: '获取单个用户',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/user/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:38:44',
            updatedat: '2022-07-21 18:38:44',
            role_ids: [14],
            parent_ids: [0, 1, 6, 68],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 68,
            children: [],
          },
          {
            id: 69,
            pid: 6,
            menu_type: 3,
            name: '根据角色获取用户',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/user/role_user',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:39:32',
            updatedat: '2022-07-21 18:39:53',
            role_ids: [14],
            parent_ids: [0, 1, 6, 69],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 69,
            children: [],
          },
          {
            id: 70,
            pid: 6,
            menu_type: 3,
            name: '设置用户状态',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/user/setStatus',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:40:27',
            updatedat: '2022-07-21 18:40:27',
            role_ids: [14],
            parent_ids: [0, 1, 6, 70],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 70,
            children: [],
          },
          {
            id: 71,
            pid: 6,
            menu_type: 3,
            name: '同步HT用户',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/user/sync',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:40:51',
            updatedat: '2022-07-21 18:40:51',
            role_ids: [14],
            parent_ids: [0, 1, 6, 71],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 71,
            children: [],
          },
          {
            id: 85,
            pid: 6,
            menu_type: 3,
            name: '登录',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/login',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:51:58',
            updatedat: '2022-07-21 18:51:58',
            role_ids: [14],
            parent_ids: [0, 1, 6, 85],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 85,
            children: [],
          },
          {
            id: 86,
            pid: 6,
            menu_type: 3,
            name: '退出',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/logout',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:52:35',
            updatedat: '2022-07-21 18:52:35',
            role_ids: [14],
            parent_ids: [0, 1, 6, 86],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 86,
            children: [],
          },
        ],
      },
      {
        id: 5,
        pid: 1,
        menu_type: 2,
        name: '日志管理',
        icon: 'AuditOutlined',
        sort: 6,
        is_hide: 1,
        route_path: '/system/log-list',
        api: '/api/v1/system/log/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-04 18:30:14',
        updatedat: '2022-08-08 15:09:53',
        role_ids: [14],
        parent_ids: [0, 1, 5],
        admin: '',
        component: 'system/log-list',
        target: '',
        redirect: '/system/log-list',
        key: 5,
        children: [
          {
            id: 74,
            pid: 5,
            menu_type: 3,
            name: '最近访问菜单',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/log/history',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:44:11',
            updatedat: '2022-07-21 18:44:11',
            role_ids: [14],
            parent_ids: [0, 1, 5, 74],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 74,
            children: [],
          },
        ],
      },
      {
        id: 38,
        pid: 1,
        menu_type: 2,
        name: '系统配置',
        icon: 'SettingOutlined',
        sort: 1,
        is_hide: 1,
        route_path: '/system/configure',
        api: '/api/v1/system/config/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-14 14:20:52',
        updatedat: '2022-07-20 16:07:38',
        role_ids: [14],
        parent_ids: [0, 1, 38],
        admin: 'duanya',
        component: 'system/configure/index',
        target: '',
        redirect: '/system/configure',
        key: 38,
        children: [
          {
            id: 72,
            pid: 38,
            menu_type: 3,
            name: '设置系统信息',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/site/set',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:42:01',
            updatedat: '2022-07-21 18:42:01',
            role_ids: [14],
            parent_ids: [0, 1, 38, 72],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 72,
            children: [],
          },
          {
            id: 73,
            pid: 38,
            menu_type: 3,
            name: '获取系统信息',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/site/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:42:42',
            updatedat: '2022-07-21 18:42:42',
            role_ids: [14],
            parent_ids: [0, 1, 38, 73],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 73,
            children: [],
          },
        ],
      },
      {
        id: 87,
        pid: 1,
        menu_type: 2,
        name: '字典管理',
        icon: 'ReadOutlined',
        sort: 1,
        is_hide: 1,
        route_path: '/system/data-dictionary/index',
        api: '/api/v1/system/config/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-27 09:38:21',
        updatedat: '2022-08-23 15:02:22',
        role_ids: [14],
        parent_ids: [0, 1, 87],
        admin: 'duanya',
        component: 'system/data-dictionary/index',
        target: '',
        redirect: '',
        key: 87,
        children: [
          {
            id: 88,
            pid: 87,
            menu_type: 3,
            name: '添加字典',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/config/add',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-27 16:00:53',
            updatedat: '2022-07-27 16:00:53',
            role_ids: [14],
            parent_ids: [0, 1, 87, 88],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 88,
            children: [],
          },
          {
            id: 89,
            pid: 87,
            menu_type: 3,
            name: '删除字典',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/config/delete',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-27 17:35:30',
            updatedat: '2022-07-27 17:35:30',
            role_ids: [14],
            parent_ids: [0, 1, 87, 89],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 89,
            children: [],
          },
          {
            id: 90,
            pid: 87,
            menu_type: 3,
            name: '编辑字典',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/config/edit',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-27 17:37:18',
            updatedat: '2022-07-27 17:37:18',
            role_ids: [14],
            parent_ids: [0, 1, 87, 90],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 90,
            children: [],
          },
          {
            id: 91,
            pid: 87,
            menu_type: 3,
            name: '获取单个字典',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/config/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-27 17:38:51',
            updatedat: '2022-07-27 17:38:51',
            role_ids: [14],
            parent_ids: [0, 1, 87, 91],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 91,
            children: [],
          },
        ],
      },
      {
        id: 96,
        pid: 1,
        menu_type: 2,
        name: '公告管理',
        icon: 'NotificationOutlined',
        sort: 0,
        is_hide: 1,
        route_path: '/system/announce/index',
        api: '/api/v1/system/announce/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-08-04 16:00:53',
        updatedat: '2022-08-05 11:19:48',
        role_ids: [14],
        parent_ids: [0, 1, 96],
        admin: 'duanya',
        component: 'system/announce/index',
        target: '',
        redirect: '',
        key: 96,
        children: [
          {
            id: 98,
            pid: 96,
            menu_type: 3,
            name: '添加公告',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/announce/add',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-08-05 11:16:24',
            updatedat: '2022-08-05 11:17:05',
            role_ids: [14],
            parent_ids: [0, 1, 96, 98],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 98,
            children: [],
          },
          {
            id: 102,
            pid: 96,
            menu_type: 3,
            name: '删除公告',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/announce/delete',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-08-08 15:07:03',
            updatedat: '2022-08-08 15:07:03',
            role_ids: [14],
            parent_ids: [0, 1, 96, 102],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 102,
            children: [],
          },
          {
            id: 103,
            pid: 96,
            menu_type: 3,
            name: '编辑公告',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/announce/edit',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-08-08 15:07:36',
            updatedat: '2022-08-08 15:07:36',
            role_ids: [14],
            parent_ids: [0, 1, 96, 103],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 103,
            children: [],
          },
          {
            id: 104,
            pid: 96,
            menu_type: 3,
            name: '获取单个公告',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/announce/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-08-08 15:08:00',
            updatedat: '2022-08-08 15:08:00',
            role_ids: [14],
            parent_ids: [0, 1, 96, 104],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 104,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 97,
    pid: 0,
    menu_type: 1,
    name: '工具',
    icon: 'AliyunOutlined',
    sort: 1,
    is_hide: 1,
    route_path: '/tools',
    api: '/',
    is_iframe: 0,
    iframe_url: '',
    createdat: '2022-08-05 11:10:48',
    updatedat: '2022-08-23 15:00:12',
    role_ids: [14],
    parent_ids: [0, 97],
    admin: 'liulinfeng',
    component: '',
    target: '',
    redirect: '',
    key: 97,
    children: [
      {
        id: 36,
        pid: 97,
        menu_type: 2,
        name: '代码生成',
        icon: 'CodeOutlined',
        sort: 1,
        is_hide: 1,
        route_path: '/generate/index',
        api: '/api/v1/system/code/list',
        is_iframe: 0,
        iframe_url: '',
        createdat: '2022-07-13 17:52:09',
        updatedat: '2022-08-05 11:15:01',
        role_ids: [14],
        parent_ids: [0, 97, 36],
        admin: 'huangzhichong',
        component: 'system/generate/index',
        target: '',
        redirect: '/generate/index',
        key: 36,
        children: [
          {
            id: 75,
            pid: 36,
            menu_type: 3,
            name: '添加代码生成配置',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/add',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:46:27',
            updatedat: '2022-08-05 15:36:25',
            role_ids: [14, 15],
            parent_ids: [36, 75],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 75,
            children: [],
          },
          {
            id: 76,
            pid: 36,
            menu_type: 3,
            name: '获取DB列表',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/db',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:46:51',
            updatedat: '2022-08-05 15:36:30',
            role_ids: [14],
            parent_ids: [36, 76],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 76,
            children: [],
          },
          {
            id: 77,
            pid: 36,
            menu_type: 3,
            name: '删除代码生成配置',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/delete',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:47:32',
            updatedat: '2022-07-21 18:47:32',
            role_ids: [14],
            parent_ids: [36, 77],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 77,
            children: [],
          },
          {
            id: 78,
            pid: 36,
            menu_type: 3,
            name: '下载代码',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/download',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:48:07',
            updatedat: '2022-07-21 18:48:07',
            role_ids: [14],
            parent_ids: [36, 78],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 78,
            children: [],
          },
          {
            id: 79,
            pid: 36,
            menu_type: 3,
            name: '修改代码生成配置',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/edit',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:48:30',
            updatedat: '2022-07-21 18:48:30',
            role_ids: [14],
            parent_ids: [36, 79],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 79,
            children: [],
          },
          {
            id: 80,
            pid: 36,
            menu_type: 3,
            name: '获取表字段',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/field',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:48:54',
            updatedat: '2022-07-21 18:48:54',
            role_ids: [14],
            parent_ids: [36, 80],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 80,
            children: [],
          },
          {
            id: 81,
            pid: 36,
            menu_type: 3,
            name: '获取代码生成配置',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/get',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:49:20',
            updatedat: '2022-07-21 18:49:20',
            role_ids: [14],
            parent_ids: [36, 81],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 81,
            children: [],
          },
          {
            id: 82,
            pid: 36,
            menu_type: 3,
            name: '预览代码',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/preview',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:49:53',
            updatedat: '2022-07-21 18:49:53',
            role_ids: [14],
            parent_ids: [36, 82],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 82,
            children: [],
          },
          {
            id: 83,
            pid: 36,
            menu_type: 3,
            name: '获取DB中的表',
            icon: '',
            sort: 0,
            is_hide: 0,
            route_path: '/',
            api: '/api/v1/system/code/table',
            is_iframe: 0,
            iframe_url: '',
            createdat: '2022-07-21 18:50:31',
            updatedat: '2022-08-05 15:39:53',
            role_ids: [14],
            parent_ids: [36, 83],
            admin: 'liulinfeng',
            component: '',
            target: '',
            redirect: '',
            key: 83,
            children: [],
          },
        ],
      },
      {
        id: 100,
        pid: 97,
        menu_type: 2,
        name: 'API文档',
        icon: 'ApiOutlined',
        sort: 1,
        is_hide: 1,
        route_path: '/iframe/index',
        api: '/iframe/v1/api',
        is_iframe: 1,
        iframe_url: 'http://admcmf.37wan.com/api/v1/document',
        createdat: '2022-08-05 14:25:04',
        updatedat: '2022-08-19 17:41:08',
        role_ids: null,
        parent_ids: [0, 97, 100],
        admin: 'huangzhichong',
        component: 'iframe/index',
        target: '',
        redirect: '',
        key: 100,
        children: [],
      },
    ],
  },
]

// console.log(arrayTreeFilter(tree, (item, level) => item.name.includes('菜单')))
console.log(JSON.stringify(filter(tree, '管理')))
